Fix warnings reported by go vet and golangci-lint
raid.go:48:44: parseMdstat - result 1 (error) is always nil (unparam)
func parseMdstat(data string) (RaidArrays, error) {

}
handler.go:187:1: cyclomatic complexity 29 of func `(*Cagent).GetAllMeasurements` is high (> 25) (gocyclo)
func (ca *Cagent) GetAllMeasurements() (common.MeasurementsMap, error) {

system.go:21:2: `unameTimeout` is unused (deadcode)
        unameTimeout    = 5 * time.Second

cmd/cagent/main.go:561:21: Error return value of `cmd.Process.Release` is not checked (errcheck)
        cmd.Process.Release()

log.go:73:15: SA4006: this value of `err` is never used (staticcheck)
        plainformat, err := hook.formatter.Format(entry)

raid.go:25:14: S1007: should use raw string (`...`) with regexp.MustCompile to avoid having to escape twice (gosimple)
var failed = regexp.MustCompile("\\[([U_]+)\\]")

# github.com/cloudradar-monitoring/cagent
./network.go:152:7: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak